author: mstiles92
description: Prevents players from regaining health due to eating food, having a full hunger bar, or potion effects.
name: NoHeal
main: com.mstiles92.noheal.NoHealPlugin
version: '0.1'
startup: postworld
permissions:
  noheal.bypass:
    description: Allows the player to heal normally.
    default: false